[toolchain]
anchor_version = "0.31.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
kwami_vault = "DoQubWtmNa4WZTLWxe1iptCDrwf81M8LHDrZDP7pEBbL"

[programs.devnet]
kwami_vault = "DoQubWtmNa4WZTLWxe1iptCDrwf81M8LHDrZDP7pEBbL"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "bun test tests/**/*.ts"
